name: ippd
description: A new Flutter project.

publish_to: 'none' 
version: 1.0.0+3

environment:
  sdk: ">=2.12.0 <3.0.0"


flutter_icons:
  android: true
  ios: true
  image_path: "assets/img/ippd.png"

dependencies:
  
  animated_splash_screen: ^1.1.0
  basic_utils: ^3.6.1
  cloud_firestore: ^2.5.1
  country_code_picker: ^2.0.2
  cupertino_icons: ^1.0.2
  cupertino_radio_choice: ^1.0.1+1
  easy_localization: ^3.0.0
  firebase_auth: ^3.1.0
  firebase_core: ^1.6.0


  
  firebase_storage: ^10.0.5
  flutter:
    sdk: flutter
  flutter_launcher_icons: 
  flutter_screenutil: ^5.0.0+2
  flutter_spinkit: ^5.1.0
  flutter_svg: ^0.22.0
  font_awesome_flutter:
  get: ^4.3.8
  google_fonts: ^2.1.0
  google_maps_flutter: ^2.0.8
  google_nav_bar: ^5.0.5
  group_button: ^3.1.0
  line_icons: ^2.0.1
  location: ^4.3.0
  page_transition: ^2.0.1-nullsafety.0
  pinput: ^1.2.0
  rflutter_alert: ^2.0.4
  shared_preferences: ^2.0.8
  syncfusion_flutter_sliders: ^19.2.59
  url_launcher: ^6.0.12

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
 

  assets:
    - assets/img/exercise/
    - assets/img/
    - assets/lang/
    

  fonts:
    - family: WorkSansSemiBold
      fonts:
        - asset: assets/fonts/Work_Sans/WorkSans-SemiBold.ttf

    - family: WorkSansBold
      fonts:
        - asset: assets/fonts/Work_Sans/WorkSans-Bold.ttf

    - family: WorkSansMedium
      fonts:
        - asset: assets/fonts/Work_Sans/WorkSans-Medium.ttf