name: ippd
description: A new Flutter project.

publish_to: 'none' 
version: 1.0.0+1

environment:
  sdk: ">=2.12.0 <3.0.0"


flutter_icons:
  android: true
  ios: true
  image_path: "assets/img/ippd.png"

dependencies:
  
  animated_splash_screen: ^1.1.0
  basic_utils: ^3.6.1
  cloud_firestore: ^2.5.1
  country_code_picker: ^2.0.2
  cupertino_icons: ^1.0.2
  cupertino_radio_choice: ^1.0.1+1
  firebase_auth: ^3.1.0
  firebase_core: ^1.6.0


  
  firebase_storage: ^10.0.5
  flutter:
    sdk: flutter
  flutter_launcher_icons: 
  flutter_svg: ^0.22.0
  font_awesome_flutter:
  get: ^4.3.8
  google_fonts: ^2.1.0
  google_maps_flutter: ^2.0.8
  google_nav_bar: ^5.0.5
  group_button: ^3.1.0
  line_icons: ^2.0.1
  location: ^4.3.0
  page_transition: ^2.0.1-nullsafety.0
  pinput: ^1.2.0
  rflutter_alert: ^2.0.4
  shared_preferences: ^2.0.8
  syncfusion_flutter_sliders: ^19.2.59
  url_launcher: ^6.0.12

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
 

  assets:
    - assets/img/exercise/dag_durusu.png
    - assets/img/exercise/duvarkay.png
    - assets/img/exercise/comelme.png
    - assets/img/exercise/dambılbukle.png
    - assets/img/exercise/dizcok.png
    - assets/img/exercise/olubocek.png
    - assets/img/exercise/triceps.png
    - assets/img/exercise/duvarit.png
    - assets/img/exercise/avkopegi.png
    - assets/img/exercise/kahraman.png
    - assets/img/exercise/duvarotur.png
    - assets/img/exercise/yanyat.png
    - assets/img/exercise/gogusomuz.png
    - assets/img/exercise/oturmusruh.png
    - assets/img/exercise/ileriakciger.png
    - assets/img/exercise/kopekpozu.png
    - assets/img/exercise/kopru.png
    - assets/img/exercise/ayaktadort.png
    - assets/img/exercise/kolcember.png
    - assets/img/exercise/cocukpozu.png
    - assets/img/exercise/tekbacak.png
    - assets/img/exercise/yalanci.png
    - assets/img/exercise/treepose.png
    - assets/img/exercise/catcow.png
    - assets/img/exercise/seatedneck.png
    - assets/img/exercise/sfenks.png
    - assets/img/exercise/seatedneck.png
    - assets/img/exercise/oturyanviraj.png
    - assets/img/exercise/duvarcomelmesi.png
    - assets/img/exercise/cesetpozu.png

    - assets/img/nurse.png
    - assets/img/kid.png
    - assets/img/nurse2.png
    - assets/img/nurse3.png
    - assets/img/ippd.png
    - assets/img/ippd2.png
    - assets/img/age.png
    - assets/img/bel.png
    - assets/img/bmi.png
    - assets/img/body.png
    - assets/img/background.png
    - assets/img/drugstore.png
    - assets/img/gender.png
    - assets/img/weight.png
    - assets/img/height.png
    - assets/img/no-smoking.png
    - assets/img/heart-disease.png
    - assets/img/check-up.png
    - assets/img/night.png
    - assets/img/water.png
    - assets/img/MBMI-0.png
    - assets/img/MBMI-1.png
    - assets/img/MBMI-2.png
    - assets/img/MBMI-3.png
    - assets/img/MBMI-4.png
    - assets/img/MBMI-5.png
    - assets/img/MBMI-6.png
    - assets/img/blood.png
    - assets/img/obesite.png
    - assets/img/diabet.png


  fonts:
    - family: WorkSansSemiBold
      fonts:
        - asset: assets/fonts/Work_Sans/WorkSans-SemiBold.ttf

    - family: WorkSansBold
      fonts:
        - asset: assets/fonts/Work_Sans/WorkSans-Bold.ttf

    - family: WorkSansMedium
      fonts:
        - asset: assets/fonts/Work_Sans/WorkSans-Medium.ttf